# General
rd_seed: 0
output_path: results  # Where to save the trained model and other outputs

# Dataset parameters
dataset:
  name: DatasetNAme         # Choose data set name for metadata saving
  path: path/to/dataset     # Path to the data set

# GNN model parameters
model:
  name: gnnModelName        # Choose model name for metadata saving
  path: path/to/model       # Path to where the model is stored at
  filebase: model-dl128-lr0.001-ep2_data-topk_test_s0     # Base name for model (remove the 'model_' or 'stats_'
                                                 # from the beginning and the '.gnn' or '.dict' from the ending)


