# General
rd_seed: 0

# Network creation configurations
network:
  model: BA       # adjacency, BA, WS, ER
  n_nodes: 3000    # Number of nodes in the generated graph -- will be ignored if model is 'adjacency'
  adjacency:      # Arguments used if model is 'adjacency'
    path: /path/to/graph/file     # TODO: Define file format | It should be a list of lists representing the adjacency matrix
  BA:   # Barabási-Albert model parameters
    m: 4          # Number of edges a new node will have when it enters the network
  WS:   # Watts-Strogatz model parameters
    k: 4          # Each node is joined with its k nearest neighbors in a ring topology.
    p: 0.3        # Probability of rewiring each edge
  ER:   # Erdös-Rényi model -- G(n,p) -- parameters
    p: 0.3        # Probability for edge creation

# Epidemic parametrization
epidemic:
  beta: 0.3             # Probability of an infected node infecting an adjacent susceptible one
  init_infec: 1         # Number of initial infected nodes
  total_time: 0         # Total time of simulation (set to 0 to disable)
  stop_frac: 0.6        # Maximum fraction of infected nodes before simulation stops (set to 0 to disable)
  observ_prob: 0.75      # Probability of an infected node being identified as infected

