# General
rd_seed: 0

# Network creation configurations
network:
  model: BA       # BA, WS, Gnp]
  parameters: 0   # TODO: Adicionar como outro dicionário? Ou como uma lista? (Acho melhor dicionário.) Deixar dentro do dicionario network ou criar esse separado mesmo?
  list_of_etc:
    - item1
    - item2       # Deixei aqui só pra mostrar que isso é possível, apagar!
# TODO

# Epidemie parametrization
epidemic:
  spread_factor: 0.1
# TODO
